# This is a development docker-compose.yml, don't use this one in production
version: "3.4"

x-gopublish-variables: &gopublish-variables
    GOPUBLISH_RUN_MODE: "prod"
    GOPUBLISH_REPOS_CONF: "test-data/sample_repos.yml"
    TZ: "Etc/UTC"


services:
    gopublish:
        build: ./
        ports:
            - 9100:80
        depends_on:
            - redis
            - db
        environment: *gopublish-variables
        volumes:
            - repos:/repos/
            - ./:/gopublish/
            - ./docker/uwsgi_dev.ini:/etc/uwsgi/uwsgi.ini:ro

    worker:
        build:
            context: .
            dockerfile: docker_celery/Dockerfile
        depends_on:
            - redis
            - db
        entrypoint: python3
        command: /opt/celery_dev_launch.py
        environment: *gopublish-variables
        volumes:
            - repos:/repos/
            - ./:/gopublish/:ro
            - ./docker_celery/celery_dev_launch.py:/opt/celery_dev_launch.py:ro

    redis:
        image: redis:4.0

    db:
        image: postgres:11-alpine
        environment:
          POSTGRES_PASSWORD: postgres

volumes:
    # A volume shared between gopublish app and worker
    repos:
